defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: sto3psl/dw-ci:1.3.0

cache: &cache
    key: v3-dependency-cache-{{ checksum "package-lock.json" }}

registry: &registry
    name: Authenticate with registry
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

version: 2
jobs:
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}

            - run:
                  <<: *registry

            - run:
                  name: Install dependencies
                  command: |
                      export DW_CONFIG_PATH=$HOME/repo/test/_config.ci.js
                      npm ci

            - save_cache:
                  <<: *cache
                  paths:
                      - node_modules
                      - ~/.npm

            - save_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
    test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run:
                  <<: *registry

            - run:
                name: Lint code
                command: npm run lint

            - run:
                  name: Run tests
                  environment:
                      DW_CONFIG_PATH: ./test/_config.ci.js
                  command: |
                      mkdir -p ~/reports/ava
                      npm test -- --tap | npx tap-xunit > ~/reports/ava/results.xml
            - run:
                  name: Cleanup DB because tests failed
                  command: npm run clean:db
                  when: on_fail
            - store_test_results:
                  path: ~/reports
            - store_artifacts:
                  path: ~/reports

workflows:
    version: 2
    install, test and lint:
        jobs:
            - install:
                  filters:
                      tags:
                          only: /^v.*/

            - test:
                  context: Testing DB
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install
